#!/bin/bash

#SBATCH --job-name=physcraper
#SBATCH --output=physcraper.out
#SBATCH --error=physcraper.err
##SBATCH --partition=sandyb
#SBATCH --time=23:10:00
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=mkandziora@ucmerced.edu


# Launch the executable 
cd physcraper
source physcraper2/bin/activate
python tests/tiny_standard_ownfile.py

